UI/Areas/Admin/Controllers/LoginController.cs
using BLL;
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: Admin/Login

        UserBLL userBll = new UserBLL();

        public ActionResult Index()
        {
            UserDTO userDto = new UserDTO();
            return View(userDto);
        }

        [HttpPost]
        public ActionResult Index(UserDTO model)
        {
            if(ModelState.IsValid)
            {
                UserDTO userDto = userBll.GetUserWithUsernameAndPassword(model);
                if (userDto.ID != 0 )
                {
                    return RedirectToAction("Index", "Post");
                } else
                {
                    return View(model);
                }
            } else
            {
                return View(model);
            }
        
        }
    }
} 

UI/Areas/Admin/Controllers/MetaController.cs
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class MetaController : Controller
    {
        // GET: Admin/Meta
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddMeta()
        {
            MetaDTO metaDto = new MetaDTO();

            return View(metaDto);
        }
    }
}

UI/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class PostController : Controller
    {
        // GET: Admin/Post
        public ActionResult Index()
        {
            return View();
        }
    }
}

UI/Areas/Admin/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}

@model DTO.UserDTO
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OAK | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link href="~/Areas/Admin/Content/CSS/all.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link href="~/Areas/Admin/Content/CSS/icheck-bootstrap.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link href="~/Areas/Admin/Content/CSS/adminlte.min.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>OAK</b></a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to start your session</p>

                <form action="@Url.Action("Index", "Login", new { area = "Admin" })" method="post">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" value="@Model.Username" placeholder="Username" name="Username">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })

                    <div class="input-group mb-3">
                        <input type="password" class="form-control" value="@Model.Password" placeholder="Password" name="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })

                    <div class="row">
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/Areas/Admin/Content/JS/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Areas/Admin/Content/JS/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Areas/Admin/Content/JS/adminlte.min.js"></script>
</body>
</html>

UI/Areas/Admin/Views/Meta/AddMeta.cshtml
@{
    ViewBag.Title = "AddMeta";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

@model DTO.MetaDTO

<section class="content-leader">
    <h1>Add Meta operation</h1>
    <ol class="breadcrumb float-sm-none" style="margin-bottom: 0px;">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Meta</a></li>
        <li class="breadcrumb-item active"><a>Add Meta</a></li>
    </ol>
</section>
<div class="card-footer">
    <button type="submit" class="btn btn-primary">Meta List</button>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            <div class="box box-primary">
                @using (Html.BeginForm("AddMeta", "Meta", new { area = "Admin" }, FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("~/Areas/Admin/Views/Meta/Partial/MetaForm.cshtml", Model)
                }
            </div>
        </div>
    </div>
</section>

UI/Areas/Admin/Views/Meta/Partial/MetaForm.cshtml
@model DTO.MetaDTO

<div class="box-body">
    <div class="form-group">
        <label>Meta Content</label>
        @Html.TextBoxFor(m => m.MetaContent, new { @class = "form-control", @placeholder = "Meta Content" })
        @Html.ValidationMessageFor(m => m.MetaContent, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Name</label>
        @Html.DropDownList("Name",
                           new SelectList(
                               new[] { "Keywords", "Description", "Author", "Twittercard" }
                           ),
                           new { @class = "form-control select2" })
    </div>
    <input type="number" name="MetaID" value="@Model.MetaID" hidden />
    <div class="card-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</div>

UI/Areas/Admin/Views/Post/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>